"""
State models for LangGraph orchestration
Defines the state that flows through the agent pipeline
"""
from typing import List, Dict, Any, Optional, Literal
from datetime import datetime
from pydantic import BaseModel, Field


class MarketData(BaseModel):
    """Market data for a single market"""
    ticker: str
    title: str
    category: str
    yes_bid: float
    yes_ask: float
    no_bid: float
    no_ask: float
    volume_24h: float
    open_interest: float
    close_date: str
    status: str
    metadata: Dict[str, Any] = Field(default_factory=dict)


class NewsData(BaseModel):
    """News article data"""
    title: str
    description: Optional[str] = None
    source: str
    url: str
    published_at: str
    content: Optional[str] = None
    sentiment_score: Optional[float] = None


class SocialData(BaseModel):
    """Social media post data"""
    platform: Literal["reddit", "twitter"]
    text: str
    score: int = 0
    created_at: str
    engagement_metrics: Dict[str, int] = Field(default_factory=dict)


class MarketAnalysis(BaseModel):
    """Complete analysis of a market including news and social sentiment"""
    market: MarketData
    news_articles: List[NewsData] = Field(default_factory=list)
    social_posts: List[SocialData] = Field(default_factory=list)
    news_sentiment: Optional[float] = None  # -1 to 1
    social_sentiment: Optional[float] = None  # -1 to 1
    combined_sentiment: Optional[float] = None
    technical_indicators: Dict[str, Any] = Field(default_factory=dict)  # RSI, momentum, volatility, etc.


class TradingSignal(BaseModel):
    """Trading signal generated by Signal Selection Agent"""
    ticker: str
    signal: Literal["LONG", "SHORT", "NO_TRADE"]
    confidence: float = Field(ge=0, le=100)  # 0-100
    expected_return: float  # Percentage
    reasoning: str
    key_factors: List[str] = Field(default_factory=list)
    risk_factors: List[str] = Field(default_factory=list)
    market_edge: str  # Why this trade has edge
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class PositionSizing(BaseModel):
    """Position sizing recommendation from Risk & Allocation Agent"""
    ticker: str
    signal: Literal["LONG", "SHORT"]
    recommended_size: int  # Number of contracts
    risk_amount: float  # Dollars at risk
    max_loss: float  # Maximum potential loss
    position_value: float  # Total position value
    stop_loss_price: float
    take_profit_price: float
    risk_reward_ratio: float
    reasoning: str


class PolicyDecision(BaseModel):
    """Final decision from Policy & Self-Critic Agent"""
    ticker: str
    decision: Literal["APPROVE", "BLOCK"]
    confidence: float = Field(ge=0, le=100)
    reasoning: str
    concerns: List[str] = Field(default_factory=list)
    checklist_results: Dict[str, bool] = Field(default_factory=dict)
    final_notes: str = ""


class ExecutionResult(BaseModel):
    """Result from Execution Agent"""
    ticker: str
    success: bool
    order_id: Optional[str] = None
    filled_quantity: int = 0
    filled_price: float = 0.0
    total_cost: float = 0.0
    error_message: Optional[str] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class CircuitBreakerStatus(BaseModel):
    """Circuit breaker status"""
    triggered: bool = False
    reason: Optional[str] = None
    severity: Literal["low", "medium", "high", "critical"] = "low"
    data_quality_ok: bool = True
    risk_limits_ok: bool = True
    api_health_ok: bool = True


class BondingOpportunity(BaseModel):
    """Bonding strategy opportunity (high-probability contracts)"""
    market: MarketData
    side: Literal["YES", "NO"]
    price: float
    return_pct: float
    days_to_close: float
    daily_return: float
    annual_return: float
    liquidity: float
    spread: float


class ArbitrageOpportunity(BaseModel):
    """Arbitrage opportunity between related markets"""
    type: Literal["within_market", "temporal", "complement", "category"]
    markets: List[str]  # Tickers involved
    profit_pct: float
    trades: List[Dict[str, Any]]  # [{ticker, side, price}, ...]
    execution_complexity: str
    confidence: float


class TradingState(BaseModel):
    """
    Main state object that flows through the LangGraph pipeline
    This represents the complete state at any point in the decision flow
    """
    # Session info
    session_id: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    cycle_number: int = 0

    # Market scanning results
    all_markets: List[MarketData] = Field(default_factory=list)
    markets_scanned: int = 0

    # Top opportunities identified
    top_opportunities: List[MarketAnalysis] = Field(default_factory=list)

    # Current market being evaluated
    current_market: Optional[MarketAnalysis] = None

    # Agent outputs (pipeline stages)
    circuit_breaker: Optional[CircuitBreakerStatus] = None
    trading_signal: Optional[TradingSignal] = None
    position_sizing: Optional[PositionSizing] = None
    policy_decision: Optional[PolicyDecision] = None
    execution_result: Optional[ExecutionResult] = None

    # New strategy opportunities
    bonding_opportunities: List[BondingOpportunity] = Field(default_factory=list)
    arbitrage_opportunities: List[ArbitrageOpportunity] = Field(default_factory=list)
    selected_bond: Optional[BondingOpportunity] = None
    selected_arbitrage: Optional[ArbitrageOpportunity] = None

    # Portfolio state
    current_balance: float = 1000.0
    open_positions: int = 0
    daily_trades: int = 0
    daily_pnl: float = 0.0

    # Capital allocation
    bonding_capital: float = 150.0  # 15% for bonding strategy
    main_capital: float = 850.0  # 85% for main strategy

    # Execution summary
    trades_executed: int = 0
    trades_blocked: int = 0
    opportunities_found: int = 0
    bonds_executed: int = 0
    arbitrages_executed: int = 0

    # Errors and warnings
    errors: List[str] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)

    # For debugging and logging
    debug_info: Dict[str, Any] = Field(default_factory=dict)

    class Config:
        arbitrary_types_allowed = True


class AgentState(BaseModel):
    """
    Simplified state for individual agent nodes
    Each agent receives this and returns updated state
    """
    state: TradingState

    class Config:
        arbitrary_types_allowed = True
